name: NodeJS with Gulp

on:
   schedule:
   - cron: "0 8 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v4.1.2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp
        
    - name: Commit changes
      run: |
        git add .
        git commit -m "Auto commit"
        git push
